# Generated by Django 4.1.7 on 2023-03-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('seria', models.CharField(max_length=100)),
                ('screen_type', models.CharField(max_length=100)),
                ('video_card', models.CharField(max_length=200)),
                ('ssd_amount', models.CharField(max_length=100)),
                ('hdd_amount', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=300)),
                ('ram_amount', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
